#!/bin/bash

# Nappyhood Salon - Complete Deployment Script
echo "🏁 Nappyhood Salon Management System - Final Deployment Steps"
echo "============================================================="
echo ""

SERVER_IP="41.186.186.178"
DOMAIN="nappyhood.com"

# Step 1: Check current status
echo "📊 Current Deployment Status:"
echo "✅ Backend API: Running at http://$SERVER_IP:5001"
echo "✅ Frontend: Running at http://$SERVER_IP:3000"
echo "✅ Database: PostgreSQL running with all data"
echo "✅ Nginx: Configured for reverse proxy"
echo ""

# Step 2: Domain DNS Setup Instructions
echo "🌐 DOMAIN SETUP REQUIRED:"
echo "=========================================="
echo "You need to configure DNS for $DOMAIN:"
echo ""
echo "DNS Records to Add:"
echo "  Type: A"
echo "  Name: @"
echo "  Value: $SERVER_IP"
echo "  TTL: 300"
echo ""
echo "  Type: A"
echo "  Name: www"
echo "  Value: $SERVER_IP"
echo "  TTL: 300"
echo ""
echo "Go to your domain registrar (GoDaddy, Namecheap, etc.) and add these records."
echo ""

# Step 3: SSL Setup Commands
echo "🔒 SSL CERTIFICATE SETUP:"
echo "=========================================="
echo "After DNS is configured (wait 5-10 minutes), run these commands on your server:"
echo ""
echo "1. SSH into your server:"
echo "   ssh -p 222 root@$SERVER_IP"
echo ""
echo "2. Test domain resolution:"
echo "   nslookup $DOMAIN"
echo ""
echo "3. Fix Nginx SSL configuration:"
echo "   apt install ssl-cert"
echo "   make-ssl-cert generate-default-snakeoil"
echo "   nginx -t && systemctl reload nginx"
echo ""
echo "4. Get Let's Encrypt certificate:"
echo "   certbot --nginx -d $DOMAIN -d www.$DOMAIN --non-interactive --agree-tos --email nappyhood.boutique@gmail.com"
echo ""

# Step 4: Final testing
echo "🧪 FINAL TESTING:"
echo "=========================================="
echo "After SSL is configured, test these URLs:"
echo ""
echo "🌐 Frontend: https://$DOMAIN"
echo "🔍 Health Check: https://$DOMAIN/health"
echo "📚 API Docs: https://$DOMAIN/api-docs"
echo "🔐 Admin Login: https://$DOMAIN/login"
echo ""

# Step 5: Admin credentials
echo "🔑 ADMIN ACCESS:"
echo "=========================================="
echo "Email: nappyhood.boutique@gmail.com"
echo "Password: admin123"
echo ""

# Step 6: Server management
echo "🛠️  SERVER MANAGEMENT:"
echo "=========================================="
echo "SSH Access: ssh -p 222 root@$SERVER_IP"
echo "App Directory: /opt/nappyhood"
echo ""
echo "Useful Commands:"
echo "  docker-compose ps                 # Check service status"
echo "  docker-compose logs -f            # View logs"
echo "  docker-compose restart            # Restart services"
echo "  docker-compose down && docker-compose up -d  # Full restart"
echo ""

# Step 7: Backup and maintenance
echo "💾 BACKUP & MAINTENANCE:"
echo "=========================================="
echo "1. Database backup:"
echo "   docker-compose exec postgres pg_dump -U postgres nappyhood_salon > backup.sql"
echo ""
echo "2. Update SSL certificate (auto-renewal is configured):"
echo "   certbot renew --dry-run"
echo ""
echo "3. Monitor logs:"
echo "   tail -f /var/log/nginx/access.log"
echo "   tail -f /var/log/nginx/error.log"
echo ""

echo "🎉 DEPLOYMENT SUMMARY:"
echo "=========================================="
echo "✅ Ubuntu Server: Configured and secure"
echo "✅ Docker: Backend + Frontend + Database running"
echo "✅ Nginx: Reverse proxy configured"
echo "✅ Firewall: Ports 80, 443, 22, 222 open"
echo "✅ SSL Ready: Certbot installed, waiting for DNS"
echo "✅ Application: Fully functional salon management system"
echo ""
echo "🚨 NEXT STEPS:"
echo "1. Configure DNS records (see above)"
echo "2. Wait 5-10 minutes for DNS propagation"
echo "3. Run SSL certificate commands"
echo "4. Test the application at https://$DOMAIN"
echo ""
echo "Your Nappyhood Salon Management System is ready! 🌿💇‍♀️"