[variables]
    NODE_ENV = "production"

[build]
    cmd = "cd backend && npm ci && npm run build && npx prisma generate"

[start]
    cmd = "cd backend && npx prisma migrate deploy && (npm run seed || echo 'Seeding failed, continuing...') && npm start"

[phases.setup]
    nixPkgs = ["nodejs_20"]