[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'cd backend && npm ci'
]

[phases.build]
cmds = [
  'cd backend && npm run build',
  'cd backend && npx prisma generate'
]

[start]
cmd = 'cd backend && npx prisma migrate deploy && npm start'