[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npx prisma generate && npx prisma migrate deploy && (npm run seed || echo 'Seeding failed, continuing...') && npm start"

[env]
NODE_ENV = "production"