[build]
builder = "RAILPACK"
buildCommand = "cd backend && npm ci && npm run build && npx prisma generate"

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && npm start"
restartPolicyType = "never"