# render.yaml — defines your backend deployment on Render

services:
  - type: web
    name: nappyhood-backend
    env: node
    rootDir: ./backend
    buildCommand: npm install && npm run build && npm run prisma:generate
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AFRICASTALKING_USERNAME
        sync: false
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false