[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build && npx prisma generate"

[start]
cmd = "npx prisma migrate deploy && (npm run seed || echo 'Seeding failed, continuing...') && npm start"